import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';
import 'package:property/config/router/app_router.dart';
import 'package:property/config/theme/app_theme.dart';
import 'package:property/core/navigation/app_navigator.dart';
import 'package:property/feature/auth/data/auth_repository.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // `firebase_options.dart` is generated by `flutterfire configure`, which
  // ties this app to one specific Firebase project — see project setup
  // notes for why that matters.
  await Firebase.initializeApp(
    options: FirebaseOptions(
      apiKey: 'AIzaSyAIAGg3IH9M1t3wDkvzgVuPmcRf7s3UGdk',
      appId: '1:1004868151524:android:2858c48e894bf70c9964f1',
      messagingSenderId: '1004868151524',
      projectId: 'property-171e0',
      storageBucket: 'property-171e0.firebasestorage.app',
    ),
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(375, 812),
      minTextAdapt: true,
      builder: (context, child) => MultiProvider(
        providers: [
          // Single shared AuthRepository instance for the whole app; the
          // router reads it to build screen-scoped providers on demand.
          Provider<AuthRepository>(create: (_) => AuthRepository()),
        ],
        child: MaterialApp(
          title: 'Property',
          debugShowCheckedModeBanner: false,
          navigatorKey: appNavigatorKey,
          theme: AppTheme.light(context),
          darkTheme: AppTheme.dark(context),
          initialRoute: AppRouteName.authGate,
          onGenerateRoute: AppRouter.onGenerateRoute,
        ),
      ),
    );
  }
}
